// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:workout_notebook/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ExerciseAdapter());
    registerAdapter(SupersetAdapter());
    registerAdapter(WorkoutAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ExerciseAdapter());
    registerAdapter(SupersetAdapter());
    registerAdapter(WorkoutAdapter());
  }
}
